### ISSUE TITLE
Problem with objects.set_()

### ISSUE THREAD

**Issue by lukakiro** [dgilland/pydash#122]
Hi,
I'm using pydash 4.7.3 on python 3.6.3 on macOS Mojave 10.14.
I have a problem with the method objects.set_().
If I execute `objects.set_({}, 'a.b', {'n':3})` everything work fine and `{'a': {'b': {'c': {'n': 3}}}}` is returned.
Instead if I execute `objects.set_({'a': None}, 'a.b.c', {'n':3})` an exception is thrown:
```python
Traceback (most recent call last):
  File "/Users/abc/.pyenv/versions/def/lib/python3.6/site-packages/pydash/objects.py", line 1668, in update_with
    target = target[key]
TypeError: 'NoneType' object is not subscriptable
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/abc/.pyenv/versions/def/lib/python3.6/site-packages/pydash/objects.py", line 1201, in set_
    return set_with(obj, path, value)
  File "/Users/abc/.pyenv/versions/def/lib/python3.6/site-packages/pydash/objects.py", line 1233, in set_with
    return update_with(obj, path, pyd.constant(value), customizer=customizer)
  File "/Users/abc/.pyenv/versions/def/lib/python3.6/site-packages/pydash/objects.py", line 1670, in update_with
    target = target[int(key)]
ValueError: invalid literal for int() with base 10: 'b'
```

Is it a bug or am I wrong?

**Comment by sumeetsarkar** [comment]
Yes, using pydash TypeError occurs, However, as per Lodash JS library, this scenarios should have worked, so this I think is a bug in pydash.

I will work on a PR for this

**Comment by sumeetsarkar** [comment]
So what I see is that in the pydash package, the objects.py module has both ```set_()``` as well as ```set_with()```

```set_with()``` supports an optional 4th parameter customizer, which is default ```None``` can take functions to customize assigned values

**Comment by sumeetsarkar** [comment]
### Example 1: Using objects.set_
```python
person1 = {
    'name': None
}
objects.set_(person1, 'name.fname', 'Sumeet')
print(person1) # outputs    {'name': None}

# objects.set_(person1, 'name.fname.abc', 'Sumeet')   # TypeError: 'NoneType' object is not subscriptable
```

### Example 2: Handling None or incomplete objects with **customizer**
```python
person2 = {
    'name': None
}

def person_customizer(value, key, obj):
    if key == 'name' and type(value) != dict:
        obj[key] = {}

objects.set_with(person2, 'name.fname.abc', 'Sumeet', person_customizer)
print(person2) # outputs    {'name': {'fname': {'abc': 'Sumeet'}}}
```

**Comment by dgilland** [comment]
This is by design: https://github.com/dgilland/pydash/blob/12571340029f75e03ad0c2d62fd8494423e59724/src/pydash/objects.py#L1665

When setting objects, overriding existing ones is not allowed by default. Per @sumeetsarkar's suggestion, using `pydash.set_with` with a customizer could be used to implement the desired behavior.

**Comment by slallum** [comment]
Still, is there a way to make this error more descriptive? it's hard to understand what causes this error right now.

**Comment by dgilland** [comment]
@slallum, Yes, I agree that the error message in this case is not super helpful. I'll add an explicit exception with a more descriptive error message about what went wrong and why it might have failed.
