### ISSUE TITLE
crash in `collections.order_by()` if ordering key is named 'value'

### ISSUE THREAD

**Issue by diogobaltazar** [dgilland/pydash#142]
Example:
```
$ python3
Python 3.7.7
[GCC 7.5.0] on linux
>>> py_.order_by([{'value': 1}], 'value')
[{'value': 1}]

>>> py_.order_by([{'value': 1}, {'value': 2}], 'value')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/pydash/collections.py", line 675, in order_by
    return sorted(collection, key=cmp_to_key(comparison), reverse=reverse)
  File "/usr/local/lib/python3.7/dist-packages/pydash/collections.py", line 669, in comparison
    result = _cmp(func(left), func(right))
  File "/usr/local/lib/python3.7/dist-packages/pydash/_compat.py", line 86, in _cmp
    def _cmp(a, b): return (a > b) - (a < b)
TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'

>>> py_.order_by([{'v': 1}, {'v': 2}], 'v')
[{'v': 1}, {'v': 2}]
```

**Comment by dgilland** [comment]
I believe this was fixed by #137.

When I try with the latest `develop` branch, I don't get an exception:

```python
>>> py_.order_by([{'value': 1}, {'value': 2}], 'value')
[{'value': 1}, {'value': 2}]
```

However, the `keys` argument to `order_by` should be a list: https://github.com/dgilland/pydash/blob/4cebf68b86d9910eb6c05f31bd49ac6bdf4a10ec/src/pydash/collections.py#L593-L596

```python
>>> py_.order_by([{'value': 2}, {'value': 1}], 'value')
[{'value': 2}, {'value': 1}]
>>> py_.order_by([{'value': 1}, {'value': 2}], ['value'])
[{'value': 1}, {'value': 2}]
```

Using a list for keys should work without the fix referenced above.
