### ISSUE TITLE
Failed to install pydash on Windows due to non-ascii char

### ISSUE THREAD

**Issue by dwettstein** [dgilland/pydash#148]
pydash fails to install on Windows with the following error:

```
Exception:
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\program files\python36\lib\site-packages\pip\commands\install.py", line 312, in run
    wheel_cache
  File "c:\program files\python36\lib\site-packages\pip\basecommand.py", line 295, in populate_requirement_set
    wheel_cache=wheel_cache):
  File "c:\program files\python36\lib\site-packages\pip\req\req_file.py", line 84, in parse_requirements
    filename, comes_from=comes_from, session=session
  File "c:\program files\python36\lib\site-packages\pip\download.py", line 422, in get_file_content
    content = auto_decode(f.read())
  File "c:\program files\python36\lib\site-packages\pip\utils\encoding.py", line 31, in auto_decode
    return data.decode(locale.getpreferredencoding(False))
  File "c:\program files\python36\lib\encodings\cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 798: character maps to <undefined>
```

This happens due to non-ascii characters in file `strings.py`:
- https://github.com/dgilland/pydash/blob/4bbadc967b51518e300a1368357bbe71959313ec/src/pydash/strings.py#L368
- https://github.com/dgilland/pydash/blob/4bbadc967b51518e300a1368357bbe71959313ec/src/pydash/strings.py#L1385

After fixing them, the installation fails with another error:
```
Collecting pydash>=4.7.6 (from -r D:\Cloudinator\Worker\test-migration-dcsplus\requirements.txt (line 28))
Exception:
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\program files\python36\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "c:\program files\python36\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\program files\python36\lib\site-packages\pip\req\req_set.py", line 664, in _prepare_file
    dist = abstract_dist.dist(finder)
  File "c:\program files\python36\lib\site-packages\pip\req\req_set.py", line 110, in dist
    self.req_to_install.source_dir))[0]
IndexError: list index out of range
```

Does the library even support installation on Windows?

**Comment by dgilland** [comment]
What version of `pip` are you using?

What are your locale settings?

**Comment by dwettstein** [comment]
Sorry, my fault, I should have included that already above.

I tried with the following versions:
```
MyServer C:\Users\MyUser>PS> python --version
Python 3.6.8
MyServer C:\Users\MyUser>PS> pip --version
pip 18.1 from c:\program files\python36\lib\site-packages\pip (python 3.6)
MyServer C:\Users\MyUser>PS>
```

After updating pip to the latest version (20.1.1 currently), I was able to install pydash. :) Sorry for bothering you.
