### ISSUE TITLE
DeprecationWarning: cgi.escape is deprecated, use html.escape instead

### ISSUE THREAD

**Issue by steveoh** [dgilland/pydash#155]
Something is up. Either the code in master hasn't been published yet or the code to figure out if I am using python 3 is fouled up.
```
File ".env/lib/python3.9/site-packages/pydash/_compat.py", line 83, in <module>
    html_escape = partial(cgi.escape, quote=True)
AttributeError: module 'cgi' has no attribute 'escape'
```

**Comment by dgilland** [comment]
I'm not seeing the same issue on my end when using Python 3.9.

```python
$ python3.9
Python 3.9.0 (default, Oct 27 2020, 14:15:17)
[Clang 12.0.0 (clang-1200.0.32.21)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pydash._compat import PY2, html_escape
>>> PY2
False
>>> import html
>>> html_escape is html.escape
True
```

Can you share your steps to reproduce the issue?

The code in `_compat.py` to determine if it's Python 2 is:

```python
import sys
PY2 = sys.version_info[0] == 2
```

Can you share what `sys.version_info` and `tuple(sys.version_info)` is for you?

**Comment by steveoh** [comment]
well, I tried to replicate what you did but...

```
Python 3.9.0 (default, Oct 27 2020, 14:15:17)
[Clang 12.0.0 (clang-1200.0.32.21)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.version_info
sys.version_info(major=3, minor=9, micro=0, releaselevel='final', serial=0)
>>> tuple(sys.version_info)
(3, 9, 0, 'final', 0)
>>>
>>> from pydash._compat import PY2, html_escape
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sgourley/dev/gis.utah.gov/.env/lib/python3.9/site-packages/pydash/__init__.py", line 19, in <module>
    from .arrays import (
  File "/Users/sgourley/dev/gis.utah.gov/.env/lib/python3.9/site-packages/pydash/arrays.py", line 13, in <module>
    from .helpers import itercallback, get_item
  File "/Users/sgourley/dev/gis.utah.gov/.env/lib/python3.9/site-packages/pydash/helpers.py", line 14, in <module>
    from ._compat import iteritems
  File "/Users/sgourley/dev/gis.utah.gov/.env/lib/python3.9/site-packages/pydash/_compat.py", line 83, in <module>
    html_escape = partial(cgi.escape, quote=True)
AttributeError: module 'cgi' has no attribute 'escape'
```

**Comment by steveoh** [comment]
ahh, pydash was for some reason installed at 3.4.7...
