### ISSUE TITLE
get goes b00m

### ISSUE THREAD

**Issue by JesterXL** [dgilland/pydash#80]
This is fine:

```python
from pydash import (
    get
)
cow = {'Body': {'result': True}}
print("cow: " + str(cow))
grab = get(cow, 'Body.result', False)
print("grab: " + str(grab))
```

However, change 'Body' to lowercase in the `get`:

```python
grab = get(cow, 'body.result', False)
```

... and she ain't so safe anymore, doesn't return false and instead raises this:

```
Traceback (most recent call last):
  File "testing.py", line 6, in <module>
    grab = get(cow, 'body.result', False)
  File "/Users/lpq389/myenv/lib/python2.7/site-packages/pydash/objects.py", line 511, in get
    obj = get_item(obj, key, default=default)
  File "/Users/lpq389/myenv/lib/python2.7/site-packages/pydash/helpers.py", line 128, in get_item
    ret = obj[int(key)]
ValueError: invalid literal for int() with base 10: 'result'
```

I'm looking at the code now to see if I can fix (I suck at Python, hence my life depending on Pydash). Workaround is to just wrap her in a try/except.

**Comment by JesterXL** [comment]
Ok, I'm confused. You don't seem to be walking the dots (i.e. "a.b.c" for example). You attempt to get the object via a key, and if that fails, you try assuming it's an int.

Anyway, here's my attempt at unwinding it with a safe default. What do you think?

```python
cow = {'Body': {'result': True}}

def return_it(acc, item):
    return acc[item]

def reduce_it(obj, path):
    dots = path.split('.')
    main = first(dots)
    unwind_that_sucka = reduce_(dots, return_it, obj)
    return unwind_that_sucka

def get2(obj, path, default):
    try:
        return reduce_it(obj, path)
    except:
        return default

wat = get2(cow, 'Body.result', False)
print("wat should be True: " + str(wat)) // True
good = get2(cow, 'body.result', False)
print("good should default to False: " + str(good)) // False
```

**Comment by dgilland** [comment]
Which version of pydash are you using?

There were a bug fixes in `3.4.6` and `3.4.7` that fixed this:

```
~/projects/pydash $ git checkout v3.4.7
~/projects/pydash $ python
Python 2.7.12 (default, Oct 17 2016, 13:28:37) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pydash
>>> cow = {'Body': {'result': True}}
>>> pydash.get(cow, 'body.result', False)
False
```

```
~/projects/pydash $ git checkout v3.4.5
~/projects/pydash $ python
Python 2.7.12 (default, Oct 17 2016, 13:28:37) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pydash
>>> cow = {'Body': {'result': True}}
>>> pydash.get(cow, 'body.result', False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydash/objects.py", line 511, in get
    obj = get_item(obj, key, default=default)
  File "pydash/helpers.py", line 128, in get_item
    ret = obj[int(key)]
ValueError: invalid literal for int() with base 10: 'result'
```

**Comment by JesterXL** [comment]
3.4.4 and 3.4.7. Lemme retry in virtualenv, one moment...

**Comment by JesterXL** [comment]
Yup, deleted my virtualenv, re-created, and all is well. Thanks!
